name: aurora-to-near-xcc-example test automatically

on: [push]

jobs:
  test-counter:
    runs-on: self-hosted
    name: Test counter
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Clone the repository
        uses: actions/checkout@v3
        with: 
          submodules: recursive
      - name: Test
        run: |
          make test-counter
